### ISSUE TITLE
CodeJam: A Cup Full of JVM

### ISSUE THREAD

**Issue by jonbullock** [NorthWalesTech/NorthWalesTech#42] opened 2016-05-01 21:14 UTC
This is something I've been thinking about for a while now. The Manchester Java Community have managed to get a few decent speakers to visit them in the past and maybe any event could be aligned with them.

There is also the Liverpool Clojure group and Manchester Scala group as well...

**Comment by carwyn** [comment] 2016-05-01 21:38
This has come up a few times now as there are a number of Java based companies in Parc Menai. Ty Menai would be a good place to have this.

I have an idea for one talk for this, a whistle-stop tour of the non Java non mainstream languages for the JVM as a bit of a light hearted break amongst the other Java talks.

**Comment by carwyn** [comment] 2016-05-01 21:58
@jonbullock one thing we did recently at Ty Menai was hold the first "Dev Talks" event which was more technical and subject specific than the more general "Tech Talks". We're expecting this to specialise even further as the group grows to allow language or technology specific sub-groups to form. We did a python specific Code Dojo a few years ago for example. It would be great if we could cater for these sub-groups while still keeping the community as a whole together with the more general events.

A regular Java (or Python/C++/Go Lang for that matter) meetup alongside the other events would be great. Could even run them as parallel tracks at a meetup with a common themed "keynote" that brings all the groups together.

**Comment by jonbullock** [comment] 2016-05-02 21:17
I only recently discovered that Ty Menai was Technium CAST so definitely a great venue... been a while since I worked in that building! 

The idea of different language tracks at a meetup sounds really good, I suppose any language specific event requires a critical mass of attendees and talks, which the more generic Dev Talks can develop over time. 

I mentioned to Rob I'd like to do a talk on Asciidoctor for tech documentation, it's Ruby based but has a bridge to the JVM languages which could sit under a common theme across different language groups, similar to your idea for non Java non mainstream JVM languages.

**Comment by anorakgirl** [comment] 2016-08-15 13:07
I'd def be interested in a Java event! @jonbullock I wonder if we could find out who they have had at The Manchester Java Community and see if we could get anyone over here?

**Comment by jonbullock** [comment] 2016-08-15 13:58
The next event is their Summer lightning talks at the end of August but I'm out of the country that week with work... would have been a good chance to share ideas and see what we could work out in terms of speakers. But I'm happy to get in touch with them once I'm back.

I noticed Chester Devs have got somebody from Elastic coming over to do a talk for them later on in the year - November time I think... maybe they'd be willing to travel a bit further down the A55 and do a NWT talk as well?

I've asked a friend who works at the BBC in Manchester to see if he'd be willing to do a talk as well.

**Comment by anorakgirl** [comment] 2016-08-15 14:05
Ooh the Elastic search one sounds good too. I guess they must pay some of these speakers.

**Comment by carwyn** [comment] 2016-08-15 14:09
Nope, Elastic are doing it for free :) Need to get the contact details off Fran :)

**Comment by jonbullock** [comment] 2016-08-15 14:10
I'm not entirely sure... from the Slack chat I saw it appeared the person offered to do a talk as he was in the area but I could be wrong.

**Comment by jonbullock** [comment] 2016-08-15 14:11
Ah didn't notice @carwyn reply before me! :)

**Comment by anorakgirl** [comment] 2016-08-15 14:12
oh cool - def worth an ask then! If not, i'd be up for another field trip...

**Comment by carwyn** [comment] 2016-08-15 14:43
@jonbullock @anorakgirl I think we should have a developer event along these lines before the end of the year :)

**Comment by jonbullock** [comment] 2016-08-15 15:49
Sounds good to me, happy to help with it too.

**Comment by jonbullock** [comment] 2016-11-14 10:49
Saw this the other day... https://twitter.com/aalmiray/status/797428487657291780

Remote sessions are one option if there was enough demand for this kind of thing.

**Comment by carwyn** [comment] 2016-11-14 11:25
Hangouts and Skype can work really well for this, I was at a conference last year in the UK where one of the speakers was remote from the US and it worked well even for the Q&A. Another idea is to try completely virtual events (although I much prefer in person).

**Comment by jonbullock** [comment] 2016-11-14 13:17
I was thinking a remote speaker presenting to a physical audience... so you don't lose that social/community aspect but wasn't sure how it would go down though with the audience though?

**Comment by davehun** [comment] 2016-11-15 09:28
It should be fine.
The RSC et. al. do something similar theatre at the cinema

**Comment by tamslinn** [comment] 2016-11-15 17:27
We could look out for conferences/events which are being live streamed, and organise a NWT event to watch together?

**Comment by jonbullock** [comment] 2016-11-15 19:02
Yeah definitely...  for JVM stuff there is always the vJUG but it's usually
just after 5pm UK time.

**Comment by carwyn** [comment] 2017-01-16 21:53
Languages of particular interest:

* Scala
* Kotlin
* JRuby
* Clojure
* Groovy

Ref: https://en.wikipedia.org/wiki/List_of_JVM_languages

**Comment by jonbullock** [comment] 2017-01-16 22:38
If we're doing lightning talks as well I don't mind doing a quick talk on Asciidoctor(J) since it's using JRuby under the hood.

**Comment by jonbullock** [comment] 2017-01-16 22:54
Do we focus on a single Kata to experiment with in each JVM language? Or follow some exercises (getting started level stuff) for each language and compare experiences?

**Comment by carwyn** [comment] 2017-01-16 23:10
Should we go for March for this?

**Comment by tamslinn** [comment] 2017-01-17 09:16
March sounds good.  With the last hands-on event, I felt I didn't have enough time for the Kata with all the talks as well. So I think we should be careful how much we try to cram in? i.e if the focus is hands-on trying non-JVM languages, a talk on that is probably enough?

On the other hand, if we just went for talks and not hands on, I could potentially do a short talk on JDBI (I was hoping to do that as part of a "my favourite library" themed set of talks !)

**Comment by tamslinn** [comment] 2017-01-17 09:16
Crazy thought - what about a thing where we split into a team for each JVM language,  each team has to complete the same challenge with their language, and we compare at the end?!

**Comment by robshep** [comment] 2017-01-17 09:20
That sounds like a neat idea.  

With The proviso that you can’t have a team member with experience for the chosen/allocated language.  Every one’s a newbie.

And it should include downloading/installing the compiler etc as that’s half the battle.

We’ll need 5 minutes per team at the end to dump code on the projector.

A challenge slightly above fizz buzz.


Bagsy Clojure!

R


— 
Rob Shepherd BEng PhD
Director / Senior Engineer - DataCymru Ltd
m: 07596154845
e: rs@datacymru.net

**Comment by carwyn** [comment] 2017-01-17 11:27
I like this idea but it doesn't really need to be at a Java event it could be at any old CodeJam.

**Comment by robshep** [comment] 2017-01-17 13:18
I was actually particular interested in an event that was focussed on “languages for the JVM” 

Kind of like a JVM shoot-out without the fatal haemorrhaging, or a royal rumble, but without any lycra. (OK Dave, you can wear Lyrca..! )

clojure
Kotlin
groovy
jruby
ceylon
java9

I’m really interested in seeing some of these in action, but have no desire to learn any on my own.

A sort of like-for-like comparison that can be done in 90mins by 3 or 4 newbies.



R

— 
Rob Shepherd BEng PhD
Director / Senior Engineer - DataCymru Ltd
m: 07596154845
e: rs@datacymru.net

**Comment by carwyn** [comment] 2017-01-17 15:20
We can but try :) Suggested dates:

Mar 7th, 9th, 14th, 16th, 21st, 23rd, 28th, 30th
Feb 7th, 9th, 21st, 23rd

Golang event is Feb 16th, Chester Devs are first Wed of month.

**Comment by anorakgirl** [comment] 2017-01-17 22:39
I'm all for a Java SIG but if we haven't (yet) got a significant amount of Java related content, this sounds like a fun alternative in the mean time

**Comment by lukepfarrar** [comment] 2017-01-18 13:54
Sounds fun :-)

**Comment by jonbullock** [comment] 2017-01-18 21:53
I like the idea too - should also give us an idea of how many in the community are interested in the JVM at least. I wouldn't mind Kotlin or Ceylon...

Only date I may not be able to do is the 23rd - supposed to be over at the Manchester Java group that night.

**Comment by carwyn** [comment] 2017-01-24 17:28
Ooh, this one's interesting reading https://dev.to/rosstate/java-is-unsound-the-industry-perspective

**Comment by carwyn** [comment] 2017-01-24 17:29
I'll pencil one in for March then?

**Comment by davehun** [comment] 2017-01-24 17:55
on the kata
I have 2 data sources (dark skies + another) that would lend them selves to a kata task:
1) record and store the data (with the associated where to run the code)
2) a later kata based on the data from task 1 (would be good opportunity for some modelling)

**Comment by davehun** [comment] 2017-01-24 17:56
how about 9/3/2017 ?

**Comment by robshep** [comment] 2017-01-24 18:06
FAKE NEWS! 

Unfortunately it’s interesting, but sensationally titled.   “Unsound", what like the foundations of a building, or BT’s European financial processes?  

Actually the title shouldn't read: "The industry perspective" because it’s the research of a few academics.

How many senior engineers or platform architects are going to trash their stack because of this? And in search of true soundness just fallback to two transistors and NAND gate?

It’s reflective anyway so if you want to break it, there are plenty of ways to play not so nice.

In my view. the compiler just catches the dumb refactoring and give the IDE half a chance at auto-completion, 
test cases stress the 90% of cases, and edge cases you might encounter to deal with regressions.
then a tried and tested hotfix and deploy strategy lets you sleep at night.



There are plenty of languages that have this kind of crazy shit - it’s a bit much to call them “unsound”

**Comment by carwyn** [comment] 2017-01-24 21:06
Indeed unsound is an academic term in this context and no none is going to trash their stack over this. It is a very interesting article to think about in the context of other languages running on the JVM though as when they implemented generics Sun elected to not retrofit modifications to explicitly cater for them into the runtime and bytecode unlike the .NET CLR. This has implications for other languages that sit on top as they either have to hold to the same rules or add additional runtime or compiler checks. This is interesting for example when you are looking at languages that are trying to add additional protection in their type or compilation systems.

**Comment by carwyn** [comment] 2017-01-24 21:50
Cast your votes (or not) for Dave's suggested date above.

**Comment by jonbullock** [comment] 2017-01-27 22:16
If somebody else really wants to use Kotlin or Ceylon I don't mind taking Groovy.

**Comment by carwyn** [comment] 2017-02-01 19:19
Another interesting one https://www.opensourcery.co.za/2017/01/05/the-jvm-is-not-that-heavy/

**Comment by carwyn** [comment] 2017-02-10 17:33
Waiting for confirmation but pencilled in the Meetup ready so we can mention it at the Golang one next week:

CodeJam: A Cup Full of JVM
https://www.meetup.com/NorthWalesTech/events/237614408/

**Comment by carwyn** [comment] 2017-02-13 17:35
Room booked, date and location added to Meetup, added @jonbullock as an event co-host. Who else wants in? @anorakgirl @davehun @robshep ?

Suggested stuff needed:

- Group lead for each language to become familiar with the runtimes to help others avoid setup frustrations. (i.e. know how to get at least "Hello World" working).
- Instructions on pre-event setup/install for the chosen runtimes (done by group leads).
  - May be little more than go to page X, do what it says.
  - Need to cover Generic Linux, OS X, Windows.
- A realistic exercise for the groups to do.
- Prod JetBrains to sponsor (via Chester Devs who already get an IDE licence per event).
  - Maybe Red Hat (Ceylon) and Oracle (good luck).
- Arrange Pizza!

**Comment by jonbullock** [comment] 2017-02-13 22:38
I'll approach JetBrains about registering NWT for the same deal. Anyone seen Red Hat so something similar at other groups?

**Comment by anorakgirl** [comment] 2017-02-13 23:38
The only language I am familiar with is groovy, although I'm more keen to have a go at one of the others. Happy to pick one and do some home work so I can  do the basics! Does anyone have preferences?

**Comment by carwyn** [comment] 2017-02-17 17:12
@anorakgirl pick one :) (not Groovy) only homework required is to know how to get **Hello World** working in the environment in question.

@jonbullock has done the legwork to get us a Jetbrains license to raffle at the event too. There are also two licences for organisers, I've suggested Jon take one if he wants it.

**Comment by carwyn** [comment] 2017-02-17 17:15
Everyone happy for me to press the Meetup announce button? A few people have found the event on there already. I can help with finding an exercise for people to do.

**Comment by robshep** [comment] 2017-02-17 18:53
I'll take a language,

Clojure?

Cheers
 Rob

**Comment by carwyn** [comment] 2017-02-17 19:16
I think @jonbullock should get Kotlin as Jetbrains make it and he got the licences for us :)

**Comment by jonbullock** [comment] 2017-02-18 00:04
I won't argue with you :)

I get an IntelliJ license for JBake so somebody else can make use of the license. And I'm happy for it to be announced too.

**Comment by robshep** [comment] 2017-02-18 00:43
Great, Thanks for the legwork guys
I'm happy to think about a common exercise also.

Involve some basic things....

* Some user input
* Consume a web service
* do something fiddly, an algorithm or a transform
* Write a file.

**Comment by carwyn** [comment] 2017-02-18 01:00
I have a real one that's quite fun that I've had to do recently, count the syllables per word in a block of text, taking diphthongs into account. It's the algorithm at the core of the Veillance generative audio. There are about half a dozen decent algorithms of varying accuracy, speed and memory consumption.

**Comment by carwyn** [comment] 2017-02-18 19:25
Other JVM language resources:

* http://www.oracle.com/technetwork/articles/java/architect-languages-2266279.html#close
* http://www.drdobbs.com/jvm/a-long-look-at-jvm-languages/240007765

Tempted to take on Javascript to see if Nashorn is any use.

**Comment by jonbullock** [comment] 2017-02-19 09:01
This is the kind of thing I'm imagining, a step up from Fizz Buzz that utilises some of the features of these other JVM languages but still small enough to fit within a single class.

https://youtu.be/Q_Z_8HXt68k

Whatever task is selected the algorithm should probably be provided in some generic form.

**Comment by carwyn** [comment] 2017-02-20 09:46
Ha! I know Russel! Often bump into him at PyConUK and end up chatting about languages at the conference dinner.

Agree, something a little more challenging but small enough to be able to implement it and discuss in the time we have (2 hours). I'm erring on thee side of suggesting everyone read through the tutorial for language you've picked but keep the exercise secret so that each group is all new to that part?

Also think having 2 to 3 steps to the exercise would be good to bring the group back together after each milestone to compare, each building on the last.

I think 3 to 4 tables at most will work. So far we have:

* Kotlin - @jonbullock 
* Clojure - @robshep 
* Ceylon - ?
* Groovy - ?
* Java 8 - @carwyn (reference implementation, no table, @davehun I last wrote Java in anger 11 years ago, this will bring back the PTSD)

I'm happy to act as timekeeper/pizza wrangler/game show host.

**Comment by tamslinn** [comment] 2017-02-20 10:27
I would vote Scala over ceylon due to greater likelihood of encountering it in the wild?

**Comment by carwyn** [comment] 2017-02-20 10:57
Oops, yes maybe Ceylon and Scala and drop Groovy? Groovy could go into a scripting CodeJam?

**Comment by davehun** [comment] 2017-02-20 11:05
lets drop java 8 and groovy

carwyn your doing either https://en.wikipedia.org/wiki/Jabaco <https://en.wikipedia.org/wiki/Jabaco> or https://en.wikipedia.org/wiki/Apache_Jelly <https://en.wikipedia.org/wiki/Apache_Jelly> ;)

Kotlin - @jonbullock <https://github.com/jonbullock>
Clojure - @robshep <https://github.com/robshep>
Ceylon - @me (unless someone else wants it)
scala
Jelly @carwyn

**Comment by jonbullock** [comment] 2017-02-20 13:37
Haha that is cruel! :wink: 

Rather than an algorithm we could pick a bunch of common tasks and see how you can achieve them in each language... inspired by this: http://www.oracle.com/technetwork/articles/java/architect-10things-2266262.html

Just an idea anyway.

**Comment by robshep** [comment] 2017-02-20 13:47
@jonbullock I think that list - or a similar variation is a perfect exercise.  A complex algorithm has it's own focus, and there only so much you can achieve in a 90min window, even in your favourite language, and in a group.

I think the aim is to allow groups of newbies to gain an extraordinarily simple appreciation of a new language, and then convey that to others.

Ignoring welcome, admin and other waffle, we're not left with a huge amount of time.
I didn't manage to fully complete fizzbuzz in ruby last time due to being somewhat social about my approach.   

I much prefer to have relaxed requirements, with an abundance of time, complete something in the social environment, then take the rest of it away for personal study.

**Comment by davehun** [comment] 2017-02-20 13:57
Yep totally agree.

Another alternative would be how any of the JVM langs we could get fizzbuzz or similar written in between the lot of us.

**Comment by jonbullock** [comment] 2017-02-20 13:59
I suppose if we do go for common development tasks then we should need less time explaining them... when compared to an algorithm that we'd need to explain to everyone.

I'm with you on the relaxed requirements too... as long you spark an interest during the event, people will carry on afterwards.

**Comment by carwyn** [comment] 2017-02-20 14:04
https://projecteuler.net/

**Comment by robshep** [comment] 2017-02-20 14:07
I don’t think we need to offer … 

"challenging mathematical/computer programming problems” 

… when it’s quite feasible to lose an hour getting a dev environment working.  

:/

— 
Rob Shepherd BEng PhD
Director / Senior Engineer - DataCymru Ltd
m: 07596154845
e: rs@datacymru.net

**Comment by carwyn** [comment] 2017-02-20 14:19
Project Euler is the one @davehun keeps wanting to do. These are more what I'd go for and are well proven. We don't need to re-invent the wheel here, some have unit test ready made too.

* http://codingdojo.org/KataCatalogue/
* https://github.com/ardalis/kata-catalog
* https://github.com/gamontalvo/awesome-katas
* http://www.codekatas.org/

@jonbullock 's 10 things is along these lines too. Tempting to pick an established Kata list and just chomp through it.

**Comment by robshep** [comment] 2017-02-20 14:20
I was thinking something trivial like this...  (but also think @jonbullock's list of common tasks is equally beneficial)

Here's an API endpoint.

    https://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&format=jsonfm&titles=Java_virtual_machine

The example above fetches the wikipedia page for the "Java Virtual Machine"

Task: write a program which does the following.

1. accept input from the user with the name of a page to fetch 
2. fetches to contents from the API
3. find the longest word and most common word
4. write the results to a file.

Having spent 2 minutes looking at clojure, I am very confident that I will fail to complete the above given 90 mins especially when I have pizza to eat and friends to talk to :)

**Comment by carwyn** [comment] 2017-02-20 14:33
How do people feel on the "each person with their own computer" vs "[mob programming](https://en.wikipedia.org/wiki/Mob_programming) per table" approaches. In the latter case there's only one computer per table with a big monitor. The latter also helps avoid issues getting runtimes to work on every attendee's computer. The downside is that people don't learn to set up the environment on their computers and take it away, but possibly spend more time thinking about the language and the exercise.

Would you guys rather play tech support or have many people watching you type? :)

**Comment by tamslinn** [comment] 2017-02-20 14:42
I really like the 10 tasks idea, as it would get you to do some things you might actually use. See which table gets the most done?

**Comment by tamslinn** [comment] 2017-02-20 14:43
Not sure about a mob of people watching me type!

**Comment by carwyn** [comment] 2017-02-20 14:45
@tamslinn you could delegate the driver's seat :) Rotating typists is another option (have visions of people spinning on office chairs).

**Comment by robshep** [comment] 2017-02-20 15:00
A bunch of pairs might be good.  With jon's list each pair can pick whatever they fancy from the list. 
I don't think it needs to be single solution.
Then we have one effort at the start where the table cooperates to get "hello world" working on half as many laptops, but then parallel learning to maximise involvement and personal input.

Although I'm not fussed either way. i'd be happy with any of it, or self organised... whatever people fancy.

**Comment by davehun** [comment] 2017-02-20 15:04
I haven’t (yet) seen a non mob event that’s inclusive.

Guess it depends on the aims if its to socialise and have fun then mobs would get my vote.



We could each set up a pi3 (any one got a spare or 2) with a collaborative web editor

**Comment by carwyn** [comment] 2017-02-20 15:09
I like @robshep 's pairs idea, seemed to work for FizzBuzz and means "mentors" aren't stuck doing one thing, while individuals still have a buddy to help. Also like the exercise menu selection as it caters for ability and pace variation. Only one of every two laptops also then needs to be hammered into submission.

**Comment by tamslinn** [comment] 2017-03-03 22:16
Just thinking about doing some prep for this! Have we decided on the kata? I quite like Rob Sheps suggestion about parsing a page from wikipedia a few pages back. Quite nice in a way to all try the same thing and then compare notes at the end?

Are we going to update the meetup with the choice of languages and get people to download/install the compiler for their choice first?

**Comment by carwyn** [comment] 2017-03-04 20:53
Are we going for Jon's "Performing 10 Routine Operations Using Different JVM Languages" or Rob's Wikipedia example? Agree we should leave time for showing the solutions people have come up with and discussion as well as the Pizza.

* Kotlin - @jonbullock 
* Clojure - @robshep 
* Scala - @anorakgirl 
* Ceylon - @davehun (if he's here).

I'm still debating putting Java or Nashorn in there, or otherwise Groovy.

@lukepfarrar are you wanting to pick a language or join in one of the above? Might be worth doubling up with Dave.

I'll add the links to the install instructions to Meetup for the languages confirmed.

**Comment by carwyn** [comment] 2017-03-04 22:07
Three languages with some of us doubling up may be the best option given time and numbers of people.

**Comment by lukepfarrar** [comment] 2017-03-04 22:36
Happy doing whatever is most useful :-)

**Comment by jonbullock** [comment] 2017-03-05 23:23
My vote goes for @robshep Wikipedia suggestion, it's simple enough to explain but complex enough to get a feel for the languages and allows for that comparison at the end as @anorakgirl suggested.

@carwyn do you want specific lang install instructions for the meetup page?

**Comment by carwyn** [comment] 2017-03-05 23:44
@jonbullock yeah a link to the download install instructions should be plenty, just so people aren't hunting and downloading. We're likely to have Linux, OS X and Windows again based on the people on the sign-up list. We have at least one person coming from Chester too.

For example for Clojure - https://clojure.org/guides/getting_started

The tricky bit might be picking the type of tooling:

* Clojure - Standalone and REPL or there's also the leiningen build env or IDE support.
* Kotlin - There are IDE and standalone options for this.
* Scala - Again standalone, build tool (sbt) or IDE.

There are two schools of thought here, often used for Java too, start with and IDE to get people moving faster but hide the details vs the standalone from scratch approach. Personally I prefer the "start with javac and a terminal" approach but many use IDEs (including CS in Bangor interestingly).

Up to you guys :) may vary per language.

**Comment by jonbullock** [comment] 2017-03-05 23:58
I'd lean towards the IDE for this event myself. But then I'd be happy to show people about SDKMAN to manage the various SDK's or build tools as well.

I'll suggest IntelliJ IDEA Community Edition for Kotlin but make sure I can get the Eclipse plugin working too.

**Comment by carwyn** [comment] 2017-03-06 00:07
Especially given we have JetBrains licenses to give away :) They all have IntelliJ language plugins.

**Comment by carwyn** [comment] 2017-03-06 20:16
Pruned comment above to pull this down here, lets go with this:

* Kotlin - @jonbullock 
* Clojure - @robshep 
* Scala - @anorakgirl 

@lukepfarrar @davehun and I the double up on the above (pick one). Better to do these well than dilute too much (based on current signup numbers). This way we can use the three table setup we had for the Go CodeJam too.

**Comment by jonbullock** [comment] 2017-03-06 20:22
Yeah sounds good to me based on the numbers.

**Comment by lukepfarrar** [comment] 2017-03-06 20:24
I'll go Clojure?

**Comment by carwyn** [comment] 2017-03-07 01:53
I've added some instructions to be meetup including the Kotlin setup ( @jonbullock can you check ) via IntelliJ. Note that the Community Edition also as built in Scala support so that could cover both. 

The IntelliJ Clojure story is a bit more complex:

* https://plugins.jetbrains.com/plugin/4050-la-clojure (old)
* https://plugins.jetbrains.com/plugin/8636-clojure-kit (newer)
* https://plugins.jetbrains.com/plugin/8090-cursive (better?)

Cursive seems to be the most impressive though:

* https://cursive-ide.com/
* https://cursive-ide.com/userguide/

But https://clojure.org/guides/getting_started may well be the best bet?

**Comment by jonbullock** [comment] 2017-03-07 09:45
Looks good to me, I've added a line about having a Java 8 JDK installed and I've also added a note about the Eclipse plugin as well.

**Comment by robshep** [comment] 2017-03-07 10:07
> Plain https://clojure.org/guides/getting_started may well be the best bet? 

I was going for this and notepad :)

**Comment by carwyn** [comment] 2017-03-07 12:15
Added to the meetup page (you all have edit access btw).

@anorakgirl @davehun which instructions would you like for Scala? Standalone, IntelliJ, sbt or other? :)

**Comment by lukepfarrar** [comment] 2017-03-07 15:32
I thought @davehun couldn't make it? He changed to not going on meetup.

**Comment by carwyn** [comment] 2017-03-07 17:08
He's on the fence. Scotland wouldn't let him in.

**Comment by jonbullock** [comment] 2017-06-30 15:22
I put Andres Almiray in contact with the Manchester Java Community and he's coming over to do a talk in August: https://www.meetup.com/ManchesterUK-Java-Community/events/238223376/

He indicated he was going to stay for a few days... is it worth asking if he'd come and do a talk at NWT as well?

**Comment by tamslinn** [comment] 2017-07-02 16:09
I'd be interested!

**Comment by carwyn** [comment] 2017-07-02 16:12
Absolutely, August would be good.

**Comment by tamslinn** [comment] 2017-07-03 08:12
Just had a look at the topics they've offered in the poll, "Java libraries you can't afford to miss" sounds good! :)

**Comment by jonbullock** [comment] 2017-07-03 10:55
OK I'll ask him.

Do we have a venue available either Wed 30th Aug or Fri 1st Sep?

**Comment by carwyn** [comment] 2017-07-03 12:42
I can arrange one :) 7pm to 9pm?

**Comment by jonbullock** [comment] 2017-07-05 20:53
Timeslot sounds good... I'm waiting to hear back what day he could do. He's travelling on the Wednesday so that day may be out depending on his travel plans... is Friday a good day for events?

**Comment by carwyn** [comment] 2017-07-05 21:00
Friday is not as good but that Friday is also the day the Byw a Bod project has its end of project conference where the students report back on their experiences. The 9 companies involved have also been invited to talk at it this time. This may allow for stacking up events together as I _think_ theirs will be daytime. I'm trying to get theirs at the end of the day with a view to running a NWT event after it.

Considering a date in September for the Summer Tech Talks too. We can make it work on either day.

@jonbullock do you mind if we split this off into another ticket. Tempted to close this one as that event happened.

**Comment by jonbullock** [comment] 2017-07-05 21:02
Yeah good idea.

**Comment by carwyn** [comment] 2017-07-05 21:08
Closed this as we've done this event (may do it again though).

**Closed by carwyn** 2017-07-05 21:08 UTC
Labels: event
